### ISSUE TITLE
Make error messages in https://crt.sh/ocsp-responders 'traceable'

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/ocsp_monitor#3]
We get plenty of messages in the columns 'Response' of https://crt.sh/ocsp-responders . It is very hard to understand, where these messages are coming from. Some seem to come from the network stack (e.g. those starting with HTTP), but many are not traceable ("unkown", "unauthorized", "verification error", "eof", "time out"). It would be great, if we could get more speaking messages, like in https://github.com/crtsh/libocsppq/pull/1 ?

**Comment by robstradling** [comment]
Addressed by https://github.com/crtsh/ocsp_monitor/commit/903a5b54be6c09d8842a37a263a456af036b8035

**Comment by RufusJWB** [comment]
> Addressed by [903a5b5](https://github.com/crtsh/ocsp_monitor/commit/903a5b54be6c09d8842a37a263a456af036b8035)

Thank you! At some steps the source of the error message is still missing:
![image](https://user-images.githubusercontent.com/1633499/143598285-7c832fcf-b091-428b-8fa2-bf749bca15f3.png)

**Comment by robstradling** [comment]
@RufusJWB After a first attempt at implementing this I decided that adding error context for everything was too noisy (e.g., "ocsp.ParseResponseForCert => Good" looks worse than "Good"), so I ultimately decided to add error context only for "real" errors.  You managed to grab that screenshot before `ocsp_monitor` had caught up with that decision.  In the code I actually committed, [OCSP response codes](https://datatracker.ietf.org/doc/html/rfc6960#section-2.3) aren't shown with any context.

**Comment by robstradling** [comment]
Perhaps "Status => Good", "Status => unauthorized", etc, would be clearer?  WDYT, @RufusJWB?

**Comment by RufusJWB** [comment]
> Perhaps "Status => Good", "Status => unauthorized", etc, would be clearer? WDYT, @RufusJWB?

My target is to understand where an error message is coming from: e.g. the network, the HTTP server or the OCSP responder. So maybe something like this would be possible:

* If no network connection at all can be created, e.g. because the OCSP URL can't be resolved, the URL is malformed or the server is not answering you use "Network ==> " as a prefix to the error message
* If a network connection can be created and the OCSP responder is replying, but not with an HTTP200 you use "OCSP Responder ==> " as a prefix followed by the returned HTTP code
* If the OCSP responder replies with an HTTP200, but there is a problem with parsing the result, you use "OCSP Parser ==>" as prefix
* If the OCSP answer can be parsed, you use as prefix "OCSP response ==>"

What do you think?

If this works, I expect some new bugs to be created in Bugzilla...
